name: work_mate
description: "A new Flutter project."

# Prevents the package from being accidentally published to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  cloud_firestore: ^5.4.1
  provider: ^6.1.2  # Corrected the provider package syntax
  google_maps_flutter: ^2.9.0
  intl: ^0.19.0  # For date and time formatting
  syncfusion_flutter_xlsio: ^26.2.14
  flutter_localizations:
    sdk: flutter  # For internationalization
  cupertino_icons: ^1.0.8  # For iOS style icons
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # Linting package to encourage good coding practices

flutter:
  uses-material-design: true

  # To add assets to your application, uncomment this section:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, uncomment this section:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
